### ISSUE TITLE
Split statistic values into separate API calls

### ISSUE THREAD

**Issue by troeger** [kubeportal/kubeportal-api-dev#1]

**Comment by kat-hi** [comment]
separate api calls using one endpoint like /statistics/< metricname> ? This is what I had in mind but I prefer to synchronize our brains.. communication over suggesting.. ;-) 

see PR: https://github.com/kubeportal/kubeportal-api-dev/pull/3

**Comment by troeger** [comment]
No, this looks good.

**Comment by kat-hi** [comment]
merged.
