### ISSUE TITLE
API Versioning

### ISSUE THREAD

**Issue by troeger** [kubeportal/kubeportal-api-dev#10]
The implemented API version should be visible for the client. How do we want to implement that?

https://restfulapi.net/versioning/

**Comment by troeger** [comment]
https://stackoverflow.com/questions/389169/best-practices-for-api-versioning

**Comment by troeger** [comment]
Let me start the discussion with the first argument: API calls should be possible with cURL / the browser. The reason is mainly laziness, there is no quicker way for testing. From my point of view, this immediately rules out versioning approaches that rely on Accept Headers, media type headers or content type headers.

**Comment by mtrx1337** [comment]
I agree with you.
Also I think we shouldn't use subdomains for versioning since that requires domain level access, but rather path based versioning (like `http://api.example.com/api/v1`).

**Comment by kat-hi** [comment]
can we first talk about the use case / the future workflow ? I think I still don't get the point.
@troeger  what is your definition of testing? 
Example: 
1. we've got this dev-api (kubeportal-api-dev) that exposes a dev-api (kubeportal-dev.api.datexis.com) via CICD that I use to develop the frontend. It is also used by Peter to sync how the api in the prod-system-branch FE-api should look like.
2. we've got a kubeportal integration where we can pull the latest "prod-api" implemented by Peter and test it against the latest frontend using docker-compose.

So, I see more than one point this discussion could be about. 
Are we talking about the dev-api (this repo) or the prod-api used in the integration-repo or the prod-api in production if changes are merged to the master? And are we talking about having more than two api-versions ONLINE (like currently the real monolith-django-backend/api, the dev-api and maybe an integration-api (where Peters Api Branch should be exposed)?

I am still not convinced of url versioning but if, I prefer subdomain-changes. it's one ingress change and I don't have to edit /adapt api-endpoints or server configurations and get in trouble with path problems or anything which forces me to touch the server/frontend code.
I will read more about all of this in the evening but I wanted to sync first what we are talking about.

**Comment by kat-hi** [comment]
...and I thought about to ignore this flask repo a bit more. maybe we should delete it and I just use it for little tests and suggestions for api-improvement. 
maintaining two dev apis and one frontend and try to sync all the time feels like "this is too much". 
I propose to only work with the integration api. I know it's more serious concerning the whole data stuff but maybe we can talk about this again @troeger. what do you think?
("This is too much" does not mean" I cannot handle the workload" but "is this really necessary?")

**Comment by troeger** [comment]
After some personal discussion, here is the wrap-up:

- The *kubeportal-api-dev* Flask code is only intended for local (offline) frontend development. This leads to to the fact that running it on a server (current CI / CD setup) is not really neccessary. This should solve @kat-hi's  "multiple APIs deployed" confusion.
- The *kubeportal-integration* repo combines frontend and backend development work. It allows itegration tests and may deploy a staging version of the whole thing on the cluster, for playing around. So, CI/CD more belongs there.
- We will end up with having a staging version and a production version of Kubeportal in live, both running in the cluster.
- Regarding API versioning, the proposal by @leonardlorenz is the right way to go. All repos will be adjusted accordingly. I propose to use SemVer, so API calls may look like this:

https://kubeportal-staging.api.example.com/v1.0.0/login

https://kubeportal.example.com/api/v1.0.0/login

After the base URL for the API (environment variable config), the full SemVer version number follows directly (code constant), and after that, the particular resource endpoint.
