### ISSUE TITLE
Archive this repo?

### ISSUE THREAD

**Issue by troeger** [kubeportal/kubeportal-api-dev#17]
Given the fact that the Flask mock is less frequently used than expected, we may want to maintain the OpenAPI spec in the Kubeportal backend repo, and put this thing here on archive mode. This would:

- Allow integration of the API specs in the Kubeportal docs
- Put pull requests for real implementation and API spec changes in one place

**Comment by kat-hi** [comment]
claro que si!

**Comment by troeger** [comment]
[WAT](https://www.destroyallsoftware.com/talks/wat)?

**Comment by kat-hi** [comment]
[it could be worse!]( https://twitter.com/yayalexisgay/status/1312914775211421700)
