### ISSUE TITLE
Allow retrieval of existing Ingress host names 

### ISSUE THREAD

**Issue by kat-hi** [kubeportal/kubeportal-api-dev#8]
@troeger I integrate the yaml-file generation and checks. 

therefore we have to discuss about these checks..
   - a)  We could request all current ingress hostname names and implement checks in FE.
   - b)  We could send the current hostname to the api and get a boolean response whether it is already used or not. But this is more than an api would do. Sounds like a "data-service" we could think about if you've got more ideas like that.

But I'd prefer the first one. If the user changes the hostname a few times, we don't have to do an api call every time. What do you think?

**Comment by troeger** [comment]
Getting a list of used ingress names from the API, for authenticated users, sounds reasonable. When you want something like red / green markers, or auto-completion, in the FE while the user is typing, then this should not lead to API roundtrips on every keypress.

I vote for a.

**Comment by kat-hi** [comment]
a!
amen.

**Comment by troeger** [comment]
Covered here: https://github.com/kubeportal/kubeportal/issues/101
